# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/source/img/ico.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockW_Scope = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockW_Scope.sizePolicy().hasHeightForWidth())
        self.dockW_Scope.setSizePolicy(sizePolicy)
        self.dockW_Scope.setMinimumSize(QtCore.QSize(36, 50))
        self.dockW_Scope.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dockW_Scope.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockW_Scope.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.dockW_Scope.setObjectName(_fromUtf8("dockW_Scope"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_qtGraph = QtGraphWrapper(self.dockWidgetContents)
        self.widget_qtGraph.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_qtGraph.sizePolicy().hasHeightForWidth())
        self.widget_qtGraph.setSizePolicy(sizePolicy)
        self.widget_qtGraph.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_qtGraph.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #000000; border-radius: 5px;"))
        self.widget_qtGraph.setObjectName(_fromUtf8("widget_qtGraph"))
        self.gridLayout_4.addWidget(self.widget_qtGraph, 0, 0, 1, 1)
        self.dockW_Scope.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockW_Scope)
        self.dockW_Parameter = QtGui.QDockWidget(MainWindow)
        self.dockW_Parameter.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dockW_Parameter.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockW_Parameter.setObjectName(_fromUtf8("dockW_Parameter"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widget_parTree = ParTreeWrapper(self.dockWidgetContents_6)
        self.widget_parTree.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_parTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_parTree.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.widget_parTree.setObjectName(_fromUtf8("widget_parTree"))
        self.gridLayout_6.addWidget(self.widget_parTree, 0, 0, 1, 1)
        self.dockW_Parameter.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockW_Parameter)
        self.dockW_Command = QtGui.QDockWidget(MainWindow)
        self.dockW_Command.setMaximumSize(QtCore.QSize(368, 240))
        self.dockW_Command.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dockW_Command.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockW_Command.setObjectName(_fromUtf8("dockW_Command"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.txt_CMD = QtGui.QPlainTextEdit(self.dockWidgetContents_7)
        self.txt_CMD.setMinimumSize(QtCore.QSize(350, 200))
        self.txt_CMD.setMaximumSize(QtCore.QSize(350, 200))
        self.txt_CMD.setObjectName(_fromUtf8("txt_CMD"))
        self.gridLayout_5.addWidget(self.txt_CMD, 0, 0, 1, 1)
        self.dockW_Command.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockW_Command)
        self.dockW_History = QtGui.QDockWidget(MainWindow)
        self.dockW_History.setMaximumSize(QtCore.QSize(368, 240))
        self.dockW_History.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dockW_History.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockW_History.setObjectName(_fromUtf8("dockW_History"))
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName(_fromUtf8("dockWidgetContents_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txt_CMD_2 = QtGui.QPlainTextEdit(self.dockWidgetContents_8)
        self.txt_CMD_2.setMinimumSize(QtCore.QSize(350, 200))
        self.txt_CMD_2.setMaximumSize(QtCore.QSize(350, 200))
        self.txt_CMD_2.setObjectName(_fromUtf8("txt_CMD_2"))
        self.gridLayout_7.addWidget(self.txt_CMD_2, 0, 0, 1, 1)
        self.dockW_History.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockW_History)
        self.action_DeviceConnect = QtGui.QAction(MainWindow)
        self.action_DeviceConnect.setObjectName(_fromUtf8("action_DeviceConnect"))
        self.action_DeviceClose = QtGui.QAction(MainWindow)
        self.action_DeviceClose.setObjectName(_fromUtf8("action_DeviceClose"))
        self.action_DeviceInfo = QtGui.QAction(MainWindow)
        self.action_DeviceInfo.setObjectName(_fromUtf8("action_DeviceInfo"))
        self.action_Start = QtGui.QAction(MainWindow)
        self.action_Start.setObjectName(_fromUtf8("action_Start"))
        self.action_Option = QtGui.QAction(MainWindow)
        self.action_Option.setObjectName(_fromUtf8("action_Option"))
        self.action_Communication = QtGui.QAction(MainWindow)
        self.action_Communication.setObjectName(_fromUtf8("action_Communication"))
        self.action_Stop = QtGui.QAction(MainWindow)
        self.action_Stop.setObjectName(_fromUtf8("action_Stop"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_SaveData = QtGui.QAction(MainWindow)
        self.action_SaveData.setObjectName(_fromUtf8("action_SaveData"))
        self.action_HelpFile = QtGui.QAction(MainWindow)
        self.action_HelpFile.setObjectName(_fromUtf8("action_HelpFile"))
        self.action_Upgrade = QtGui.QAction(MainWindow)
        self.action_Upgrade.setObjectName(_fromUtf8("action_Upgrade"))
        self.action_Update = QtGui.QAction(MainWindow)
        self.action_Update.setObjectName(_fromUtf8("action_Update"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menu.addAction(self.action_DeviceConnect)
        self.menu.addAction(self.action_DeviceClose)
        self.menu.addSeparator()
        self.menu.addAction(self.action_DeviceInfo)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Exit)
        self.menu_2.addAction(self.action_Start)
        self.menu_2.addAction(self.action_Stop)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_SaveData)
        self.menu_3.addAction(self.action_Communication)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_Option)
        self.menuAbout.addAction(self.action_HelpFile)
        self.menuAbout.addAction(self.action_Update)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.action_About)
        self.menuTools.addAction(self.action_Upgrade)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ScopeAcq", None))
        self.menu.setTitle(_translate("MainWindow", "Device", None))
        self.menu_2.setTitle(_translate("MainWindow", "Acquire", None))
        self.menu_3.setTitle(_translate("MainWindow", "Setting", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockW_Scope.setWindowTitle(_translate("MainWindow", "Scope", None))
        self.dockW_Parameter.setWindowTitle(_translate("MainWindow", "Parameter", None))
        self.dockW_Command.setWindowTitle(_translate("MainWindow", "Command", None))
        self.dockW_History.setWindowTitle(_translate("MainWindow", "History", None))
        self.action_DeviceConnect.setText(_translate("MainWindow", "DeviceConnect", None))
        self.action_DeviceClose.setText(_translate("MainWindow", "DeviceClose", None))
        self.action_DeviceInfo.setText(_translate("MainWindow", "DeviceInfo", None))
        self.action_Start.setText(_translate("MainWindow", "Start", None))
        self.action_Option.setText(_translate("MainWindow", "Option", None))
        self.action_Communication.setText(_translate("MainWindow", "Communication", None))
        self.action_Stop.setText(_translate("MainWindow", "Stop", None))
        self.action_Exit.setText(_translate("MainWindow", "Exit", None))
        self.action_SaveData.setText(_translate("MainWindow", "SaveData", None))
        self.action_HelpFile.setText(_translate("MainWindow", "HelpFile", None))
        self.action_Upgrade.setText(_translate("MainWindow", "Upgrade", None))
        self.action_Update.setText(_translate("MainWindow", "Update", None))
        self.action_About.setText(_translate("MainWindow", "About", None))

from partreewrapper import ParTreeWrapper
from qtgraphwrapper import QtGraphWrapper
import pyimg_rc
